### ISSUE TITLE
THATS A BIG ISSUE

### ISSUE THREAD

**Issue by AEKHer** [Artado-Project/Nova-Search#1]
I have a issue.It's not nice to use my anime girlfriend's photo while doing a search engine.

**Comment by YasinSenpai** [comment]
I'm sorry brother but your girlfriend so hot

**Comment by AEKHer** [comment]
U too

**Comment by YasinSenpai** [comment]
bro my gf is not a anime girl...

**Comment by AEKHer** [comment]
I meant you, not your girlfriend

**Comment by YasinSenpai** [comment]
ramadan haram brother

**Comment by AEKHer** [comment]
it was just a joke bro i'm not gay i'm on the artist's way
